class_name LoadBus extends RefCounted

const first_level: String = "res://now/dungeon/cave/origin/0/0/level.tscn"
const fight: String = "res://now/see/fight.tscn"
const ground: String = "res://now/see/ground.tscn"
const whip: String = "res://now/see/whip.tscn"
const pull: String = "res://now/see/ledges.tscn"
const ledges: String = "res://now/see/ledges.tscn"
const health: String = "res://now/work/health/%s.tscn"
const ability: String = "res://now/work/lockers/ability/%s.tscn"
const activator: String = "res://now/work/lockers/ability/%s.tscn"
const music: String = "res://now/work/music.tscn" # const hero: String = "res://now/work/hero/%s/%s.tscn"
const ray: String = "res://now/work/hero/ray/ray.tscn"
const rock: String = "res://now/work/hero/rock/rock.tscn"
const group: String = "res://now/work/group/%s.tscn"
const level: String = "res://asset/system/scene/usable/level/%s/%s/%d/level.tscn"
const hud: String = "res://now/hud/%s.tscn"
const credits: String = "res://now/credits.tscn"
const settings: String = "res://now/settings.tscn"
const sound: String = "res://now/sound.tscn"
const information: String = "res://now/information.tscn"
const pause: String = "res://now/hud/status/pause.tscn"
const slots: String = "res://now/hud/status/slots.tscn"
const enemy: String = "res://now/hud/status/enemy.tscn"
const hints: String = "res://now/hud/hints/%s.tscn"
const hp: String = "res://now/hud/markers/health.tscn"
const items: String = "res://now/hud/markers/items.tscn"
const actions: String = "res://now/work/hero/actions/%s.tscn"
const xp: String = "res://now/hud/status/xp.tscn"
const hits: String = "res://now/hud/status/hits.tscn"
const game: String = "res://now/hud/game/%s.tscn"
const mirror: String = "res://now/see/mirror/%s.tscn"
const input: String = "res://now/work/hero/%s/%s.tscn"
const world: String = "res://now/work/hero/world/%s.tscn"
