class_name LoadBus extends RefCounted

var fight: String:
	get: return "res://now/see/fight.tscn"
var ground: String:
	get: return "res://now/see/ground.tscn"
var whip: String:
	get: return "res://now/see/whip.tscn"
var pull: String:
	get: return "res://now/see/ledges.tscn"
var ledges: String:
	get: return "res://now/see/ledges.tscn"
var health: String:
	get: return "res://now/work/health/%s.tscn"
var ability: String:
	get: return "res://now/work/lockers/ability/%s.tscn"
var activator: String:
	get: return "res://now/work/lockers/ability/%s.tscn"
var music: String:
	get: return "res://now/work/music.tscn"
var hero: String:
	get: return "res://now/work/hero/%s/%s.tscn"
var group: String:
	get: return "res://now/work/group/%s.tscn"
var level: String:
	get: return "res://asset/system/scene/usable/level/%s/%s/%d/level.tscn"
var hud: String:
	get: return "res://now/hud/%s.tscn"
var credits: String:
	get: return "res://now/credits.tscn"
var settings: String:
	get: return "res://now/settings.tscn"
var sound: String:
	get: return "res://now/sound.tscn"
var information: String:
	get: return "res://now/information.tscn"
var pause: String:
	get: return "res://now/hud/status/pause.tscn"
var slots: String:
	get: return "res://now/hud/status/slots.tscn"
var enemy: String:
	get: return "res://now/hud/status/enemy.tscn"
var hints: String:
	get: return "res://now/hud/hints/%s.tscn"
var hp: String:
	get: return "res://now/hud/markers/health.tscn"
var items: String:
	get: return "res://now/hud/markers/items.tscn"
var actions: String:
	get: return "res://now/work/hero/actions/%s.tscn"
var xp: String:
	get: return "res://now/hud/status/xp.tscn"
var hits: String:
	get: return "res://now/hud/status/hits.tscn"
var game: String:
	get: return "res://now/hud/game/%s.tscn"
var mirror: String:
	get: return "res://now/see/mirror/%s.tscn"
var input: String:
	get: return "res://now/work/hero/%s/%s.tscn"
var world: String:
	get: return "res://now/work/hero/world/%s.tscn"
